[package]
name = "voter-registry"
version = "0.1.0"
authors = ["Felipe Sere <felipesere@gmail.com>"]
edition = "2018"

[dependencies]
ring = "0.13.5"
rocket = "0.4.0"
untrusted = "0.6.2"
rocket_contrib = "0.4.0"
serde = "1.0.83"
serde_derive = "1.0.83"
base64 = "0.10.0"
